baseURL = 'https://projetos-ept.github.io/parasitologia/'
languageCode = 'pt-br'
title = 'Parasitologia Cl√≠nica'
theme = 'book'
publishDir = 'docs'

defaultContentLanguage = 'pt-br'
enableEmoji = true

[params]
  BookTheme = 'light'
  BookSection = '*'
  BookToC = true
  BookMenuBundle = '/'
